return {
  ["\"GM_STALL_SHELF_TYPE_OVERTIME\""] = "Expirado",
  ["\"GM_STALL_SHELF_TYPE_SELLING\""] = "Área de venda",
  ["\"CHINESE_MAX\""] = "Máx.",
  ["\"GM_STALL_SHELF_TYPE_PUBLICITY\""] = "Área de Publicidade",
  ["\"UTILS_TIME_FORMAT_SECOND_STR\""] = "%s segundos",
  ["\"UTILS_TIME_FORMAT_DAY_STR\""] = "%s dias",
  ["\"CONST_QUARTER_DESC\""] = "Trimestre",
  ["\"CONST_MONTH_DESC\""] = "Mês",
  ["\"CONST_WEEK_DESC\""] = "Semana",
  ["\"CONST_DAY_DESC\""] = "Dia",
  ["\"GM_MODIFY_STALL_RECORD_FAILED_NOT_FOUND_RECORD\""] = "Falha na execução: nenhum registro encontrado para o jogador especificado. Id do jogador: %d",
  ["\"GM_MODIFY_STALL_RECORD_FAILED_STATE_ERROR\""] = "Falha na execução: o status atual do registro de revisão [ %d ] não é um status de falha. Falha na modificação. Jogador gbId: %d , Item uuid: %s",
  ["\"GM_MODIFY_STALL_RECORD_SUCCESS\""] = "Execução bem-sucedida: registro de revisão modificado com sucesso. Jogador gbId: %d , Item uuid: %s",
  ["\"GM_EXE_SUCCESS_CENSOR_NOT_PASS\""] = "Execução bem-sucedida: revisão rejeitada. Jogador gbId: %d , Item uuid: %s",
  ["\"EXPLORE_TIPS_TITLE\""] = "Detalhes do progresso da exploração",
  ["\"GM_EXE_SUCCESS_CENSOR_PASS\""] = "Execução bem-sucedida: revisão aprovada. Jogador gbId: %d , Item uuid: %s",
  ["\"PHOTO_ALBUM\""] = "Álbum",
  ["\"GM_EXE_FAILED_NOT_FOUND_CENSOR_ITEM\""] = "Falha na execução: nenhum registro encontrado para o item de revisão especificado. Jogador gbId: %d , Item uuid: %s",
  ["\"CHINESE_YOU_RESP\""] = "Você",
  ["\"GM_NOT_FOUND_STALL_ITEM\""] = "Item especificado não encontrado. Por favor, confirme se os parâmetros estão corretos.",
  ["\"CHINESE_MIN\""] = "Mínimo",
  ["\"GM_REMOVE_ITEM_NO_RET\""] = "%s item(s) listado(s) removido(s), quantidade: %d \n",
  ["\"UTILS_TIME_FORMAT_MINUTE_STR\""] = "%s minutos",
  ["\"GM_REMOVE_ITEM_AND_RET\""] = "%s item(s) listado(s) removido(s), quantidade: %d . Itens devolvidos ao jogador \n",
  ["\"UTILS_TIME_FORMAT_HOUR_STR\""] = "%s horas",
}
